/**
 * Build dist/ bundles.
 *
 * ponytail: bundles only the 2D studio (src/), not the legacy 3D engine.
 * animateEngine.js is already a self-contained UMD file and Phase 3 will gut
 * it, so splitting it into modules now is churn that gets rewritten.
 */
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

// The TTS runtime is fetched from a pinned CDN url at runtime and must stay a
// live dynamic import; bundling it would also drag in onnxruntime-web, which
// only resolves through the page's import map.
const external = ['https://*'];
const common = { bundle: true, format: undefined, target: 'es2022', external, logLevel: 'warning' };

const outputs = [
    { entryPoints: ['src/studio.js'], outfile: 'dist/jirex.esm.js', format: 'esm' },
    { entryPoints: ['src/studio.js'], outfile: 'dist/jirex.esm.min.js', format: 'esm', minify: true },
    { entryPoints: ['src/studio.js'], outfile: 'dist/jirex.js', format: 'iife', globalName: 'jireX' },
    { entryPoints: ['src/studio.js'], outfile: 'dist/jirex.cjs', format: 'cjs', platform: 'neutral' },
    { entryPoints: ['src/studio.js'], outfile: 'dist/jirex.min.js', format: 'iife', globalName: 'jireX', minify: true },
    { entryPoints: ['src/core/index.js'], outfile: 'dist/jirex-core.esm.js', format: 'esm' },
    { entryPoints: ['src/core/index.js'], outfile: 'dist/jirex-core.esm.min.js', format: 'esm', minify: true },
];

const results = [];
for (const o of outputs) {
    const r = await build({ ...common, ...o, metafile: true });
    const bytes = Object.values(r.metafile.outputs)[0].bytes;
    results.push({ file: o.outfile, kb: +(bytes / 1024).toFixed(1) });
}

writeFileSync('dist/README.md',
    '# dist\n\nGenerated by `npm run build`. Do not edit.\n\n'
    + results.map((r) => `- \`${r.file.replace('dist/', '')}\` — ${r.kb} KB`).join('\n') + '\n');

console.table(results);
