/**
 * Compile the Rust kernels to WebAssembly and embed them as a JS module.
 *
 *   npm run build:wasm
 *
 * # Why the wasm is embedded rather than fetched
 *
 * The obvious design is to ship `jirex_kernels.wasm` as a file and
 * `fetch` it. In a browser that invites a specific set of failures, all of
 * which present as "the fast path silently never loads":
 *
 *   - the path is wrong under a bundler, a CDN, a sub-path deploy or a
 *     service worker's scope;
 *   - the server does not send `Content-Type: application/wasm`, so
 *     `instantiateStreaming` rejects;
 *   - the page is opened from `file://`, where fetch is blocked outright;
 *   - CORS blocks a cross-origin fetch from a CDN build.
 *
 * Base64 in a module has none of those. It costs about a third more bytes
 * -- 21 KB becomes 28 KB -- which against any real asset in this engine
 * is noise, and it means the kernels load wherever the JS loaded, with no
 * configuration at all. A caller who would rather fetch can still pass
 * bytes to `loadKernels({ wasmBytes })`.
 *
 * This also keeps the browser dependency count at zero: there is nothing
 * to install, nothing to resolve, and no network request that can fail.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const crate = join(root, 'rust', 'jirex-kernels');
const out = join(root, 'src', 'kernels', 'wasm', 'module.js');

// Run with `cwd` set to the crate, not with `--manifest-path` from the
// repository root. Cargo discovers `.cargo/config.toml` by walking up from
// the *current working directory*, not from the manifest's directory, so
// building by manifest path from elsewhere silently drops the crate's
// `rustflags` -- which is where `-C target-feature=+simd128` lives. The
// build still succeeds; it just produces a scalar module, and the only
// visible symptom is `has_simd()` returning 0.
console.log('cargo build --release --target wasm32-unknown-unknown (cwd: rust/jirex-kernels)');
execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown'],
    { stdio: 'inherit', cwd: crate });

const wasmPath = join(crate, 'target', 'wasm32-unknown-unknown', 'release', 'jirex_kernels.wasm');
const wasm = readFileSync(wasmPath);

// Refuse to embed a module that needs anything from the host. The whole
// portability claim rests on the import list being empty, so it is checked
// here rather than trusted -- adding a dependency to the crate that pulls
// in `wasi` or `getrandom` would otherwise fail much later and much less
// clearly.
const mod = await WebAssembly.compile(wasm);
const imports = WebAssembly.Module.imports(mod);
if (imports.length) {
    console.error('refusing to embed: the module imports', JSON.stringify(imports));
    console.error('kernels must be self-contained -- no WASI, no JS glue, no host functions.');
    process.exit(1);
}
const exported = new Set(WebAssembly.Module.exports(mod).map((e) => e.name));
for (const required of ['memory', 'alloc', 'dealloc', 'abi_version']) {
    if (!exported.has(required)) {
        console.error(`refusing to embed: missing required export "${required}"`);
        process.exit(1);
    }
}

// The flag this build was actually compiled with, read back from the
// module rather than assumed from the config file -- see the cwd note
// above for why assuming it was wrong once already.
const probe = await WebAssembly.instantiate(mod, {});
const simd = !!probe.exports.has_simd?.();
if (!simd) {
    console.error('refusing to embed: built without simd128.');
    console.error('check rust/jirex-kernels/.cargo/config.toml is being picked up.');
    process.exit(1);
}

const b64 = wasm.toString('base64');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `/**
 * The compiled Rust kernels, base64-encoded.
 *
 * GENERATED by scripts/build-wasm.mjs -- do not edit. Rebuild with
 * \`npm run build:wasm\` after changing anything under rust/jirex-kernels.
 *
 * Source: ${wasm.length} bytes of wasm, ${b64.length} as base64.
 * Imports: none, verified at build time.
 */

const BYTES = '${b64}';

/**
 * Decode the embedded module to bytes.
 *
 * \`atob\` is global in browsers and in Node 16+, so one path covers both;
 * the \`Buffer\` branch is only a faster route when it happens to exist.
 */
export function wasmBytes() {
    if (typeof Buffer !== 'undefined') return new Uint8Array(Buffer.from(BYTES, 'base64'));
    const raw = atob(BYTES);
    const out = new Uint8Array(raw.length);
    for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
    return out;
}

/** Byte length of the decoded module, without decoding it. */
export const WASM_SIZE = ${wasm.length};
`);

console.log(`embedded ${wasm.length} bytes (${b64.length} base64) -> src/kernels/wasm/module.js`);
console.log('imports: none · exports:', exported.size, '· simd128:', simd);
